global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'device-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['device-service:8081']

  - job_name: 'scene-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['scene-service:8082']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8083']

  - job_name: 'analytics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['analytics-service:8084']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'